### ISSUE TITLE
Install rails admin or similar

### ISSUE THREAD

**Issue by sjobe** [sjobe/fong4life#67]
https://github.com/sferik/rails_admin 

For easily CRUDing data.

**Comment by newton10471** [comment]
Did you consider Active Admin?  http://activeadmin.info/  We use it, and it's awesome.  If you're more familiar or like rails_admin better, then cool, but if you don't have a preference, I'd at least look at Active Admin.

**Comment by sjobe** [comment]
Nice, will check active admin out. I don't really have a strong preference, as long as it plays nice with mongo.

**Comment by sjobe** [comment]
Active admin not playing nice with Mongoid + Rails 4. We're going to use the Admin UI provided on heroku for MongoDB for now and see how well that works.
